#ifndef HTTP_HPP
# define HTTP_HPP

enum t_http_status {
    HTTP_STATUS_OK = 200,

    HTTP_STATUS_FOUND = 302,

    HTTP_STATUS_BAD_REQUEST = 400,
    HTTP_STATUS_UNAUTHORIZED = 401,
    HTTP_STATUS_FORBIDDEN = 403,
    HTTP_STATUS_NOT_FOUND = 404,
    HTTP_STATUS_METHOD_NOT_ALLOWED = 404,
    HTTP_STATUS_URI_TOO_LONG = 414,
    HTTP_STATUS_IM_A_TEAPOT = 418,

    HTTP_STATUS_INTERNAL_SERVER_ERROR = 500,
    HTTP_STATUS_NOT_IMPLEMENTED = 501,
    HTTP_STATUS_BAD_GATEWAY = 502,
    HTTP_STATUS_SERVICE_UNAVAILABLE = 503,
    HTTP_STATUS_VERSION_NOT_SUPPORTED = 505,
    HTTP_STATUS_DUMMY = 0
};



#endif
